// Composant utilitaire pour centraliser les icônes Lucide et améliorer le tree-shaking
export { 
  Users,
  BookOpen, 
  Calendar, 
  FileCheck, 
  Accessibility, 
  Search, 
  MessageSquareWarning, 
  ClipboardCheck, 
  Database,
  Plus,
  Filter,
  Eye,
  Edit,
  Trash2,
  Loader2,
  BarChart3,
  Clock,
  CheckCircle,
  Globe,
  Laptop,
  Code,
  ShoppingBag,
  Lightbulb,
  Sparkles,
  FileDown,
  ArrowLeft,
  FileSpreadsheet,
  FileUp
} from "lucide-react";